server:
  port: 8082

spring:
  application:
    name: pub
  cloud:
    function:
      definition: courseSupplier;textSupplier
    stream:
      function:
        definition: courseSupplier;textSupplier
      bindings:
        courseSupplier-out-0:
          destination: mw1
          content-type: application/json
        textSupplier-out-0:
          destination: mw2
          content-type: text/plain
      poller:
        fixed-delay: 5000
      kafka:
        binder:
          brokers: localhost:9092






#  kafka:
#    bootstrap-servers: localhost:9092
#
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#
#  cloud:
#    function:
#      definition: upperCase
#      function.web.path: /upperCase